apps/main/urls.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django.conf.urls import url
from django.contrib.auth.views import login, logout


# Third party apps imports


# Local imports
from .views import (
    SaucersListView, SaucerCreateView, SaucerUpdateView, SaucerDeleteView,
    UsersListView, UserCreateView, UserDeleteView, login_waitress,
    OrderListView, OrderCreateView, order_send_kitchen, order_send_table,
    order_send_table_from_kitchen, OrderDeleteView)

# Create your tests here.


urlpatterns = [
    url(
        r'^platillos/$',
        SaucersListView.as_view(),
        name='index'
    ),
    url(
        r'^platillos/crear/$',
        SaucerCreateView.as_view(),
        name='saucer_create'
    ),
    url(
        r'^platillos/actualizar/(?P<id>\d+)/$',
        SaucerUpdateView.as_view(),
        name='saucer_update'
    ),
    url(
        r'^platillos/eliminar/(?P<id>\d+)/$',
        SaucerDeleteView.as_view(),
        name='saucer_delete'
    ),
    url(
        r'^usuarios/$',
        UsersListView.as_view(),
        name='users'
    ),
    url(
        r'^usuarios/crear/$',
        UserCreateView.as_view(),
        name='user_create'
    ),
    url(
        r'^usuarios/eliminar/(?P<id>\d+)/$',
        UserDeleteView.as_view(),
        name='user_delete'
    ),
    url(
        r'^$',
        login,
        name='login',
        kwargs={'template_name': 'main/login.html'}
    ),
    url(
        r'^logout/$',
        logout,
        name='logout',
        kwargs={'next_page': '/'}
    ),
    url(
        r'^login-mesero/$',
        login_waitress,
        name='login_waitress',
    ),
    url(
        r'^mesero/panel/(?P<table_selected>\d+)/$',
        OrderListView.as_view(),
        name='panel_waitress',
    ),
    url(
        r'^mesero/agregar-pedido/(?P<table_selected>\d+)/$',
        OrderCreateView.as_view(),
        name='panel_create',
    ),
    url(
        r'^mesero/mandar-cocina/(?P<table_selected>\d+)/(?P<order_id>\d+)/$',
        order_send_kitchen,
        name='send_kitchen',
    ),
    url(
        r'^mesero/mandar-mesa/(?P<table_selected>\d+)/(?P<order_id>\d+)/$',
        order_send_table,
        name='send_table',
    ),
    url(
        r'^cocinero/mandar-mesa/(?P<order_id>\d+)/$',
        order_send_table_from_kitchen,
        name='send_table_from_kitchen',
    ),
    url(
        r'^mesero/eliminar/(?P<table_selected>\d+)/(?P<id>\d+)/$',
        OrderDeleteView.as_view(),
        name='order_delete'
    ),
]

chibi_chickens/urls.py
# -*- coding: utf-8 -*-
"""chibi_chickens URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin


from apps.locations import urls as locations_urls
from apps.main import urls as main_urls


urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include(locations_urls, namespace='locations')),
    url(r'^', include(main_urls, namespace='main')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

apps/locations/models.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django.db import models


# Third party apps imports


# Local imports
from .managers import OrderQuerySet


# Create your models here.
class Saucer(models.Model):

    STATE_CHOICES = (
        ('no disponible', 'No disponible'),
        ('agotado', 'agotado'),
        ('en stock', 'En Stock'),)

    name = models.CharField(max_length=50, verbose_name='Nombre', unique=True)
    price = models.DecimalField(
        max_digits=7, decimal_places=2, verbose_name='Precio')
    state = models.CharField(
        choices=STATE_CHOICES, max_length=50, verbose_name='Estado')
    quantity = models.PositiveSmallIntegerField(verbose_name='Cantidad')

    class Meta:
        verbose_name = 'Platillo'
        verbose_name_plural = 'Platillos'

    def __unicode__(self):
        return '{0} - S/. {1}'.format(self.name, self.price)


class Table(models.Model):

    capacity = models.PositiveSmallIntegerField(
        verbose_name='Cantidad de personas')
    number = models.PositiveSmallIntegerField(
        unique=True, verbose_name='Numero de mesa')

    class Meta:
        verbose_name = 'Mesa'
        verbose_name_plural = 'Mesas'

    def __unicode__(self):
        return '{0}'.format(self.number)


class Order(models.Model):

    STATE_CHOICES = (
        ('solicitado', 'Solicitado'),
        ('preparando', 'Preparando'),
        ('para servir', 'Para servir'),
        ('cancelado', 'Cancelado'),
        ('servido', 'Servido'),)

    table = models.ForeignKey(Table, verbose_name='Mesa')
    saucer = models.ForeignKey(Saucer, verbose_name='Platillo')
    quantity = models.PositiveSmallIntegerField(
        blank=True, null=True, verbose_name='Cantidad')
    state = models.CharField(
        choices=STATE_CHOICES, max_length=50, verbose_name="Estado")

    objects = OrderQuerySet.as_manager()

    class Meta:
        verbose_name = 'Orden'
        verbose_name_plural = u'Órdenes'

    def __unicode__(self):
        return '{0}'.format(self.table.number)

apps/main/models.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django.db import models


# Third party apps imports


# Local imports


# Create your models here.

apps/main/forms.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django import forms


# Third party apps imports


# Local imports
from apps.locations.models import Saucer


# Create your forms here.

apps/main/views.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.shortcuts import resolve_url
from django.template.response import TemplateResponse
from django.utils.http import is_safe_url
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import CreateView, ListView, UpdateView, DeleteView


# Third party apps imports
from braces.views import LoginRequiredMixin


# Local imports
from apps.locations.models import Saucer, Table, Order


# Create your views here.
@sensitive_post_parameters()
@csrf_protect
@never_cache
def login_waitress(
        request, template_name='main/login_waitress.html',
        redirect_field_name=REDIRECT_FIELD_NAME,
        authentication_form=AuthenticationForm, current_app=None,
        extra_context=None):
    redirect_to = request.POST.get(
        redirect_field_name, request.GET.get(redirect_field_name, ''))

    if request.method == "POST":
        form = authentication_form(request, data=request.POST)
        if form.is_valid():
            if request.POST['table'] == 'Seleccionar Mesa':
                return redirect(reverse('main:login_waitress'))
            if not is_safe_url(url=redirect_to, host=request.get_host()):
                redirect_to = resolve_url(reverse(
                    'main:panel_waitress',
                    kwargs={'table_selected': request.POST['table']}))
            auth_login(request, form.get_user())
            return HttpResponseRedirect(redirect_to)
    else:
        form = authentication_form(request)

    current_site = get_current_site(request)
    context = {
        'form': form,
        redirect_field_name: redirect_to,
        'site': current_site,
        'site_name': current_site.name,
        'tables': Table.objects.all()
    }

    if extra_context is not None:
        context.update(extra_context)

    if current_app is not None:
        request.current_app = current_app

    return TemplateResponse(request, template_name, context)


class SaucersListView(LoginRequiredMixin, ListView):

    template_name = 'main/saucers.html'
    login_url = '/'
    context_object_name = 'saucers'
    model = Saucer
    queryset = Saucer.objects.all()

    def get_context_data(self, **kwargs):
        context = super(SaucersListView, self).get_context_data(**kwargs)
        context.update({
            'menu': 'saucers',
            'orders': Order.objects.all().order_by('table__number')
        })
        return context


class SaucerCreateView(LoginRequiredMixin, CreateView):

    model = Saucer
    fields = ('name', 'price', 'state', 'quantity',)

    def get_success_url(self):
        return reverse('main:index')

    def form_invalid(self, form):
        return redirect(reverse('main:index'))


class SaucerUpdateView(LoginRequiredMixin, UpdateView):

    model = Saucer
    fields = ('name', 'price', 'state', 'quantity',)
    pk_url_kwarg = 'id'
    template_name = 'main/saucers.html'

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('main:index')

    def form_invalid(self, form):
        return redirect(reverse('main:index'))


class SaucerDeleteView(LoginRequiredMixin, DeleteView):

    model = Saucer
    pk_url_kwarg = 'id'

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('main:index')


class UsersListView(LoginRequiredMixin, ListView):

    context_object_name = 'employees'
    model = User
    template_name = 'main/users.html'
    login_url = '/'

    def get_queryset(self):
        return User.objects.filter(
            groups__name__in=[
                'administradores', 'meseros', 'cocineros']).exclude(
                    id=self.request.user.id).order_by('username')

    def get_context_data(self, **kwargs):
        context = super(UsersListView, self).get_context_data(**kwargs)
        context.update({
            'menu': 'users'
        })
        return context


class UserCreateView(LoginRequiredMixin, CreateView):

    model = User
    fields = ('username', 'password', 'first_name', 'last_name', 'groups',)

    def get_success_url(self):
        return reverse('main:users')

    def form_invalid(self, form):
        return redirect(reverse('main:users'))

    def form_valid(self, form):
        try:
            user = User.objects.create_user(
                form.cleaned_data['username'], '',
                form.cleaned_data['password'])
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.groups = form.cleaned_data['groups']
            user.save()
        except Exception as e:
            print str(e)
        return redirect(reverse('main:users'))


class UserDeleteView(LoginRequiredMixin, DeleteView):

    model = User
    pk_url_kwarg = 'id'

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('main:users')


class OrderListView(ListView):
    context_object_name = 'orders'
    model = Order
    template_name = 'main/orders.html'
    queryset = Order.objects.all().order_by('table__number')

    def get_context_data(self, *args, **kwargs):
        context = super(OrderListView, self).get_context_data(**kwargs)
        context.update({
            'table_selected': self.request.path_info.split('/')[3]
        })
        return context


class OrderCreateView(LoginRequiredMixin, CreateView):

    model = Order
    fields = ('table', 'saucer', 'quantity', 'state',)
    template_name = 'main/order_create.html'

    def get_success_url(self):
        return reverse(
            'main:panel_waitress',
            kwargs={'table_selected': self.request.path_info.split('/')[3]})

    def get_context_data(self, *args, **kwargs):
        context = super(OrderCreateView, self).get_context_data(**kwargs)
        context.update({
            'orders': Order.objects.all().order_by('table__number'),
            'saucers': Saucer.objects.all().order_by('name'),
            'table_selected': self.request.path_info.split('/')[3]
        })
        return context

    def form_valid(self, form):
        saucer = form.cleaned_data['saucer']
        order_quantity = form.cleaned_data['quantity']
        if saucer.quantity - order_quantity >= 0:
            saucer.quantity -= order_quantity
            if saucer.quantity == 0:
                saucer.state = 'agotado'
            saucer.save()
            self.object = form.save()
        else:
            return redirect(reverse(
                'main:panel_create',
                kwargs={'table_selected': self.path_info.split('/')[3]}))

        return super(OrderCreateView, self).form_valid(form)


@login_required
def order_send_kitchen(self, table_selected, order_id):
    order = Order.objects.get(id=order_id)
    order.state = 'preparando'
    order.save()
    return redirect(reverse(
        'main:panel_waitress',
        kwargs={'table_selected': table_selected}))


@login_required
def order_send_table(self, table_selected, order_id):
    order = Order.objects.get(id=order_id)
    order.state = 'servido'
    order.save()
    return redirect(reverse(
        'main:panel_waitress',
        kwargs={'table_selected': table_selected}))


@login_required
def order_send_table_from_kitchen(self, order_id):
    order = Order.objects.get(id=order_id)
    order.state = 'para servir'
    order.save()
    return redirect(reverse('main:index'))


class OrderDeleteView(LoginRequiredMixin, DeleteView):

    model = Order
    pk_url_kwarg = 'id'

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse(
            'main:panel_waitress',
            kwargs={'table_selected': self.kwargs['table_selected']})

apps/main/templates/main/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block titulo %}{% endblock %} | Polleria Chibi Chicken</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'main/css/app.min.css' %}" />
        <style>
            .modal-backdrop{
                display: none !important;
            }
        </style>
    </head>
    <body>
        {% block cuerpo_mesero %}
            <div class="container-layout">
                <div class="content-layout">
                    {% block navegacion %}
                        <nav class="content-aside">
                            <div class="logo">
                                <img src="{% static 'main/img/pollo.png' %}" alt="">
                                <h4>Chibi Chiken</h4>
                            </div>
                            <ul class="nav navbar-nav">
                                <li {% ifequal menu 'saucers' %}class="active"{% endifequal %}><a href="{% url 'main:index' %}"><i class="fa fa-chevron-right" aria-hidden="true"></i> Platillos</a></li>
                                <li {% ifequal menu 'users' %}class="active"{% endifequal %}><a href="{% url 'main:users' %}"><i class="fa fa-chevron-right" aria-hidden="true"></i> Usuarios</a></li>
                                <li><a href="{% url 'main:logout' %}">Cerrar Sesión</a></li>
                            </ul>
                        </nav>
                    {% endblock navegacion %}
                    {% block cuerpo %}{% endblock cuerpo %}
                </div>
            </div>
            {% if messages %}
            <div class="row">
                <br/>
                <div class="col-md-12">
                    {% for message in messages %}
                        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
                    {% endfor %}
                </div>
            </div>
            {% endif %}
        {% endblock cuerpo_mesero %}
        <script type="text/javascript" src="{% static 'main/js/jquery.js' %}"></script>
        <script type="text/javascript" src="{% static 'main/js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'main/js/app.js' %}"></script>
    </body>
</html>

apps/main/templates/main/order_create.html
{% extends "main/base.html" %}
{% load staticfiles %}





{% block titulo %}Panel Mesero{% endblock %}





{% block cuerpo_mesero %}
<nav class="navbar navbar-color">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Chibi Chiken</a>
        </div>
        <!-- Note that the .navbar-collapse and .collapse classes have been removed from the #navbar -->
        <div id="navbar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'main:panel_create' table_selected %}">Registrar Pedidos</a></li>
                <li class="active"><a href="{% url 'main:panel_waitress' table_selected %}">Mesas</a></li>
                <li><a href="{% url 'main:logout' %}">Cerrar Sesion</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form class="form-modal" method="post">{% csrf_token %}
                <div class="form-group">
                    <select id="id_table" class="form-control" name="table">
                        <option value="{{ table_selected }}">Mesa # : {{ table_selected }}</option>
                    </select>
                </div>
                <div class="form-group">
                    <select id="id_saucer" class="form-control" name="saucer">
                        <option value="" selected="selected">Platillo</option>
                        {% for saucer in saucers %}
                            {% ifnotequal saucer.quantity 0 %}
                                <option value="{{ saucer.id }}">{{ saucer }}</option>
                            {% endifnotequal %}
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <input class="form-control" id="id_quantity" min="0" name="quantity" type="number" placeholder="Cantidad">
                </div>
                <div class="form-group">
                    <select id="id_state" class="form-control" name="state">
                        <option value="" selected="selected">Estado</option>
                        <option value="solicitado">Solicitado</option>
                        <option value="preparando">Preparando</option>
                        <option value="cancelado">Cancelado</option>
                        <option value="servido">Servido</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-success">Agregar</button>
            </form>
            <br>
            <div class="table-responsive">
                <table id="mytable" class="table table-bordred table-striped">
                    <thead>
                        <th>Nombre Platillo</th>
                        <th>Costo por Unidad</th>
                        <th>Cantidad</th>
                        <th>Estado Platillo</th>
                    </thead>
                    <tbody>
                        {% for saucer in saucers %}
                            <tr>
                                <td>{{ saucer.name }}</td>
                                <td>S/. {{ saucer.price }}</td>
                                <td>{{ saucer.quantity }}</td>
                                <td>{{ saucer.state }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/main/templates/main/orders.html
{% extends "main/base.html" %}
{% load staticfiles %}





{% block titulo %}Panel Mesero{% endblock %}





{% block cuerpo_mesero %}
<nav class="navbar navbar-color">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Chibi Chiken</a>
        </div>
        <!-- Note that the .navbar-collapse and .collapse classes have been removed from the #navbar -->
        <div id="navbar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'main:panel_create' table_selected %}">Registrar Pedidos</a></li>
                <li class="active"><a href="{% url 'main:panel_waitress' table_selected %}">Panel de Pedidos</a></li>
                <li><a href="{% url 'main:logout' %}">Cerrar Sesion</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <!-- <div class="clearfix">
                <h4>Ingresar numero de Mesa</h4>
                <div class="b_centerForm">
                    <form id="custom-search-form" class="form-search form-horizontal">
                        <div class="input-append span12">
                            <input type="text" class="search-query" placeholder="Search">
                            <button type="submit" class="btn"><i class="fa fa-search"   aria-hidden="true"></i></button>
                        </div>
                    </form>
                </div>
            </div> -->
            <br>
            <div class="table-responsive">
                <table id="mytable" class="table table-bordred table-striped">
                    <thead>
                        <th>Nombre Platillo</th>
                        <th>Cantidad</th>
                        <th>Costo del Platillo</th>
                        <th>Costo total del Pedido</th>
                        <th>Mesa</th>
                        <th>Estado Pedido</th>
                        <th>Mandar a Cocina</th>
                        <th>Mandar a Mesa</th>
                        <th>Limpiar Mesa</th>
                    </thead>
                    <tbody>
                        {% for order in orders %}
                            <tr>
                                <td>{{ order.saucer.name }}</td>
                                <td>{{ order.quantity }}</td>
                                <td>S/. {{ order.saucer.price }}</td>
                                <td>S/. {% widthratio order.saucer.price 1 order.quantity %}</td>
                                <td>{{ order.table.number }}</td>
                                <td>{{ order.state }}</td>
                                <td>
                                    {% ifequal order.state 'solicitado' %}
                                    <a href="{% url 'main:send_kitchen' table_selected order.id %}"><button type="submit" class="btn btn-success">Enviar</button></a>
                                    {% endifequal %}
                                </td>
                                <td>
                                    {% ifequal order.state 'para servir' %}
                                    <a href="{% url 'main:send_table' table_selected order.id %}"><button type="submit" class="btn btn-success">Enviar</button></a>
                                    {% endifequal %}
                                </td>
                                <td>
                                    {% ifequal order.state 'servido' %}
                                    <a href="{% url 'main:order_delete' table_selected order.id %}"><button type="submit" class="btn btn-success">Enviar</button></a>
                                    {% endifequal %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/main/templates/main/users.html
{% extends "main/base.html" %}
{% load staticfiles %}





{% block titulo %}Usuarios{% endblock titulo %}





{% block cuerpo %}
{% for group in user.groups.all %}
    {% ifequal group.name 'administradores' %}



        <div class="content-main clearfix">
            <div class="clearfix">
                <h4 class="title-option">Lista de Usuarios <button class="btn-agregar" data-title="Agregar" data-toggle="modal" data-target="#agregar" ><i class="fa fa-plus" aria-hidden="true"></i></span></button></h4>
                <div class="col-xs-12">
                    <div class="table-responsive">
                        <table id="mytable" class="table table-bordred table-striped">
                            <thead>
                                <th>Nombre</th>
                                <th>Apellido</th>
                                <th>Username</th>
                                <th>Categoría</th>
                                <th>Eliminar</th>
                            </thead>
                            <tbody>
                                {% for employee in employees %}
                                    <tr>
                                        <td>{{ employee.first_name }}</td>
                                        <td>{{ employee.last_name }}</td>
                                        <td>{{ employee.username }}</td>
                                        <td>{{ employee.groups.all.0 }}</td>
                                        <td>
                                            <button class="btn-table-delete" data-title="Delete" data-toggle="modal" data-target="#delete{{ employee.id }}" ><i class="fa fa-trash" aria-hidden="true"></i></span></button>

                                            <div class="modal fade" id="delete{{ employee.id }}" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
                                                <div class="modal-dialog">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times" aria-hidden="true"></i></button>
                                                            <h4 class="modal-title custom_align" id="Heading">Eliminar Usuario</h4>
                                                        </div>
                                                        <div class="modal-body">
                                                          <div class="alert alert-danger">Esta seguro de eliminar al usuario {{ employee.first_name }} {{ employee.last_name }}?</div>
                                                        </div>
                                                        <div class="modal-footer ">
                                                            <a href="{% url 'main:user_delete' employee.id %}"><button type="button" class="btn btn-success" >ACEPTAR</button></a>
                                                            <button type="button" class="btn btn-default" data-dismiss="modal">CANCEL</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>




        <div class="modal fade" id="agregar" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times" aria-hidden="true"></i></button>
                        <h4 class="modal-title custom_align" id="Heading">Crear Usuario</h4>
                    </div>
                    <div class="modal-body">
                        <form class="form-modal" action="{% url 'main:user_create' %}" method="POST">{% csrf_token %}
                            <div class="form-group">
                                <input id='id_first_name' name="first_name" class="form-control" type="text"    placeholder="Nombres">
                            </div>
                            <div class="form-group">
                                <input id='id_last_name' name="last_name" class="form-control" type="text" placeholder="Apellidos">
                            </div>
                            <div class="form-group">
                                <input id='id_username' name="username" class="form-control" type="text" placeholder="Username">
                            </div>
                            <div class="form-group">
                                <input id='id_password' name="password" class="form-control" type="password" placeholder="Contraseña">
                            </div>
                            <div class="form-group">
                                <select id='id_groups' class="form-control" name="groups">
                                    <option value="" selected="selected">Categoria</option>
                                    <option value="1">Administrador</option>
                                    <option value="2">Mesero</option>
                                    <option value="3">Cocinero</option>
                                </select>
                            </div>
                            <div class="modal-footer ">
                                <button type="submit" class="btn btn-success" >ACEPTAR</button>
                                <button type="button" class="btn btn-default" data-dismiss="modal">CANCEL</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endifequal %}
{% endfor %}
{% endblock cuerpo %}